"""Configuration loaded from environment variables / .env."""

from __future__ import annotations

from pathlib import Path

from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    """Server settings.

    Loaded from environment variables first, then `.env` file. Values are also
    exposed through the `/v1/config` endpoint so the Android client can adjust
    a few things at runtime (default `max_iterations`, default model, etc.).
    """

    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        env_prefix="SUZU_",
        extra="ignore",
    )

    # Server
    host: str = "0.0.0.0"
    port: int = 8765
    log_level: str = "info"

    # Auth — shared bearer token, generated by install.sh, pasted into the app
    token: str = "change-me-please"

    # Workspace root — agent's working directory; one subdir per session
    workspace_root: Path = Path("workspace")

    # Database
    db_path: Path = Path("sessions.db")

    # Agent defaults
    default_model: str = "claude-3-5-sonnet-20241022"
    default_max_iterations: int = 100
    default_max_tokens: int = 4096

    # Tools — paths to bundled CLIs (resolved by install.sh)
    apktool_jar: Path = Path("/opt/suzu-tools/apktool.jar")
    jadx_bin: Path = Path("/opt/suzu-tools/jadx/bin/jadx")
    apksigner_bin: Path = Path("apksigner")
    zipalign_bin: Path = Path("zipalign")

    # Per-tool safety limits
    shell_timeout_seconds: int = 600
    shell_max_output_bytes: int = 1_000_000
    file_max_read_bytes: int = 2_000_000


settings = Settings()
